# Generated by Django 4.2 on 2025-04-20 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('html_content', models.TextField(verbose_name='HTML 내용')),
                ('text_content', models.TextField(verbose_name='텍스트 내용')),
                ('email_date', models.DateField(verbose_name='이메일 날짜')),
                ('is_generated', models.BooleanField(default=True, verbose_name='생성 완료')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('daily_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_emails', to='contents.dailycontent', verbose_name='일일 콘텐츠')),
            ],
            options={
                'verbose_name': '일일 이메일',
                'db_table': 'daily_emails',
                'ordering': ['-email_date'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='템플릿명')),
                ('subject', models.CharField(max_length=200, verbose_name='이메일 제목')),
                ('html_content', models.TextField(verbose_name='HTML 내용')),
                ('text_content', models.TextField(verbose_name='텍스트 내용')),
                ('template_type', models.CharField(choices=[('daily_content', '일일 콘텐츠'), ('welcome', '가입 환영'), ('verification', '이메일 인증')], default='daily_content', max_length=20, verbose_name='템플릿 유형')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to='contents.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '이메일 템플릿',
                'db_table': 'email_templates',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='수신 이메일')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('sent', '발송됨'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('scheduled_at', models.DateTimeField(verbose_name='예약 시간')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('daily_email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='mailing.dailyemail', verbose_name='일일 이메일')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='subscriptions.subscription', verbose_name='구독')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '이메일 로그',
                'db_table': 'email_logs',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyemail',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_emails', to='mailing.emailtemplate', verbose_name='사용 템플릿'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status'], name='email_logs_status_e3be55_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['scheduled_at'], name='email_logs_schedul_8ed15b_idx'),
        ),
    ]
