# Generated by Django 4.2 on 2025-04-27 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('pending', '대기 중'), ('sent', '발송됨'), ('bounced', '반송됨'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태'),
        ),
        migrations.CreateModel(
            name='SampleEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='수신 이메일')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('sent', '발송됨'), ('bounced', '반송됨'), ('failed', '실패')], default='pending', max_length=10, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='발송 시간')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('daily_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_email_logs', to='mailing.dailyemail', verbose_name='일일 이메일')),
            ],
            options={
                'verbose_name': '샘플 이메일 로그',
                'verbose_name_plural': '샘플 이메일 로그',
                'db_table': 'sample_email_logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sampleemaillog',
            index=models.Index(fields=['recipient_email'], name='sample_emai_recipie_d36af2_idx'),
        ),
        migrations.AddIndex(
            model_name='sampleemaillog',
            index=models.Index(fields=['sent_at'], name='sample_emai_sent_at_5da825_idx'),
        ),
    ]
