# Generated by Django 4.2 on 2025-04-27 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('mailing', '0002_alter_emaillog_status_sampleemaillog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleemaillog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sample_email_logs', to='contents.category', verbose_name='카테고리'),
        ),
    ]
