# Generated by Django 4.2 on 2025-05-02 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('mailing', '0003_sampleemaillog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='이메일 주소')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='시작일')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='종료일')),
                ('status', models.CharField(choices=[('active', '활성'), ('completed', '완료됨'), ('cancelled', '취소됨'), ('converted', '정규 구독으로 전환됨')], default='active', max_length=20, verbose_name='상태')),
                ('preferred_time', models.TimeField(default='07:00', verbose_name='선호 시간')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '체험 구독',
                'verbose_name_plural': '체험 구독 목록',
                'db_table': 'trial_subscriptions',
                'unique_together': {('email', 'category')},
            },
        ),
        migrations.CreateModel(
            name='TrialEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='수신 이메일')),
                ('subject', models.CharField(max_length=200, verbose_name='제목')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('sent', '발송됨'), ('bounced', '반송됨'), ('failed', '실패')], default='pending', max_length=20, verbose_name='상태')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='예약 시간')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='발송 시간')),
                ('day_number', models.IntegerField(default=1, verbose_name='체험 일차')),
                ('daily_email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.dailyemail', verbose_name='일일 이메일')),
                ('trial_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='mailing.trialsubscription', verbose_name='체험 구독')),
            ],
            options={
                'verbose_name': '체험 이메일 로그',
                'verbose_name_plural': '체험 이메일 로그 목록',
                'db_table': 'trial_email_logs',
            },
        ),
    ]
