# Generated by Django 4.2 on 2025-05-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_trialsubscription_trialemaillog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trialemaillog',
            options={'verbose_name': '체험 이메일 로그'},
        ),
        migrations.AlterModelOptions(
            name='trialsubscription',
            options={'verbose_name': '체험 구독'},
        ),
    ]
