# Generated by Django 4.2 on 2025-04-20 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='카테고리명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='contents.category', verbose_name='상위 카테고리')),
            ],
            options={
                'verbose_name': '카테고리',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='DailyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('additional_info', models.TextField(blank=True, verbose_name='추가 설명')),
                ('scheduled_date', models.DateField(verbose_name='예약일')),
                ('is_sent', models.BooleanField(default=False, verbose_name='발송 여부')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='출처')),
                ('url', models.URLField(blank=True, verbose_name='참조 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_contents', to='contents.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '일일 콘텐츠',
                'db_table': 'daily_contents',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
