# Generated by Django 4.2 on 2025-05-06 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_passwordless',
            field=models.BooleanField(default=False, verbose_name='회원가입 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='management_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='사용자 관리 UUID 토큰'),
        ),
    ]
