# Generated by Django 4.2 on 2025-05-06 14:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_passwordless_user_management_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='management_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='사용자 관리 UUID 토큰'),
        ),
    ]
