# Generated by Django 4.2 on 2025-05-06 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_management_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='management_token',
        ),
    ]
