# Generated by Django 4.2 on 2025-05-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('preferred_time', models.TimeField()),
                ('frequency', models.CharField(default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verification_token', models.UUIDField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.category')),
            ],
            options={
                'db_table': 'pending_subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
